### PR TITLE
feat: add rust-serde-json src

### PR DESCRIPTION
**Pull request by Komorebi-yaodong**
JSON serialization file format.

Log: rust-serde-json src would be added.

Issue: https://github.com/deepin-community/sig-deepin-sysdev-team/issues/148

### CODE REVIEW

**Comment by Komorebi-yaodong** [comment]
@chenchongbiao 麻烦老师检查一下这个PR

**Comment by Zeno-sole** [comment]
@Komorebi-yaodong  依赖不满足，缺少的依赖应该没提交

**Comment by chenchongbiao** [comment]
arm架构编译提示缺 librust-itoa-1+default-dev,我看rust-itoa这个是obs编译过了 @Zeno-sole

**Pull request merged**
